version: "3.8"

services:
  postgresql-master:
    image: 'docker.io/bitnami/postgresql:14'
    container_name: "pg-master"
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    networks:
      - fullstack
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=postgres
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1

  postgresql-slave1:
    image: 'docker.io/bitnami/postgresql:14'
    container_name: "pg-slave1"
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    networks:
      - fullstack
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=postgres

  golang-prod:
    build: .
    container_name: "golang-prod"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - fullstack

  golang:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "golang"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: gin -p 8080 /app/main.go
    depends_on:
      - postgres
    networks:
      - fullstack

  redis:
    image: redis:6.0-buster
    ports:
      - "6379:6379"
    container_name: 'redis'
    networks:
      - fullstack
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./storage/data:/data
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"

#  migrate:
#    image: migrate/migrate
#    container_name: "migrate"
#    networks:
#      - fullstack
#    volumes:
#      - ./database/migrations:/migrations
#    depends_on:
#      - postgres
#    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable", "down", "1"]

networks:
  fullstack:
    driver: bridge

volumes:
  database_postgres:
  postgresql_master_data:
    driver: local