version: "3.8"

services:
  pg-master:
    image: 'docker.io/bitnami/postgresql:14'
    container_name: "pg-master"
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    networks:
      - fullstack
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=postgres
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1

  pg-slave:
    image: 'docker.io/bitnami/postgresql:14'
    container_name: "pg-slave"
    ports:
      - '5433:5432'
    restart: always
    depends_on:
      - pg-master
    networks:
      - fullstack
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=postgres

  dcard-project:
    build: .
    container_name: "dcard-project"
    ports:
      - "8080:8080"
    depends_on:
      - pg-master
      - pg-slave
      - redis
    networks:
      - fullstack

  golang:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "golang"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: gin -p 8080 /app/main.go
    depends_on:
      - pg-master
      - pg-slave
      - redis
    networks:
      - fullstack

  redis:
    image: redis:6.0-buster
    ports:
      - "6379:6379"
    container_name: 'redis'
    networks:
      - fullstack
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"

  migrate:
    image: migrate/migrate
    container_name: "migrate"
    networks:
      - fullstack
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@pg-master:5432/postgres?sslmode=disable", "up"]

networks:
  fullstack:
    driver: bridge

volumes:
  redis_data:
  postgresql_master_data:
    driver: local