// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "description": "請輸入合法原網址",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Url"
                ],
                "summary": "產生短網址",
                "parameters": [
                    {
                        "description": "Get Short Url",
                        "name": "url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUrl"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ApiUrl"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ApiUrl": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Meta Description"
                },
                "image": {
                    "type": "string",
                    "example": "Meta Image Url"
                },
                "short_url": {
                    "type": "string",
                    "example": "5Cb"
                },
                "title": {
                    "type": "string",
                    "example": "Meta title"
                }
            }
        },
        "model.CreateUrl": {
            "type": "object",
            "properties": {
                "org_url": {
                    "type": "string",
                    "example": "https://www.google.com"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
