name: Go

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Fetch required Go modules
        run: go clean --modcache

      - name: Fetch required Go modules
        run: go mod download

      - name: Build
        run: go build ./cmd/app/main.go

#      - name: Test
#        run: go test -v ./test

  deploy:
    runs-on: ubuntu-latest
    needs: build
#    if: startsWith(github.ref, 'refs/tags')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/golang:latest
