name: Go

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Fetch required Go modules
        run: go mod download

      - name: Test
        run: go test -v ./tests

      - name: Test-1
        run: echo "Hello tag ${{ github.ref }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
#    if: startsWith(github.ref, 'refs/tags')
    steps:
#      - name: Extract Version
#        id: version_step
#        run: |
#          echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"
#          echo "##[set-output name=version_tag;]$GITHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/v"}"
#          echo "##[set-output name=latest_tag;]$GITHUB_REPOSITORY:latest"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

#      - name: Set up Docker Buildx1
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USER_NAME }}
#          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
##
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile.dev
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/golang:latest